server:
  port: 8888
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

spring:
  application:
    name: picture-manage-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picture
    username: root
    password: 986532asd
      # Redis 配置
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 5000
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
  session:
    store-type: redis
    timeout: 2592000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-not-delete-value: 0 #未删除
      logic-delete-value: 1 #已删除


knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    openapi-version: 3.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.muli.picturemanage.controller
